name: Build, Deploy, and Push Frontend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install dependencies
      - name: Install Dependencies
        run: npm install

      # Build the React-Vite app
      - name: Build App
        run: npm run build

      # Archive build artifacts
      - name: Archive Production Files
        uses: actions/upload-artifact@v3
        with:
          name: production-build
          path: dist/

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Download build artifacts from the previous job
      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: production-build

      # Build a Docker image
      - name: Build Docker Image
        run: |
          docker build -t your-dockerhub-username/frontend-nginx:latest -f Dockerfile .

      # Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Push the Docker image to DockerHub
      - name: Push Docker Image
        run: |
          docker push knutekje/frontend-nginx:latest

      # Test the Docker image (optional)
      - name: Test Deployment
        run: |
          docker run -d -p 80:80 knutekje/frontend-nginx:latest
          curl -I http://localhost | grep "200 OK"
